spring:
    application:
        name: micoserice-zipkin-server
    zipkin:
        base-url: http://localhost:9994 
        sleuth:
            sampler:
            percentage: 1.0
server:
    port: 9994
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1001/eureka/
    instance:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true