spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: consul-test
  application:
    name: consul-test
server:
  port: 8502